### ISSUE TITLE
URL needs to be ASCII

### ISSUE THREAD

**Issue by Jmuccigr** [ryanfb/academia-dl#1]
Getting this error 

`.rbenv/versions/2.6.4/lib/ruby/2.6.0/uri/rfc3986_parser.rb:21:in `split': URI must be ascii only`

on this URL:

`https://www.academia.edu/1963397/Santuario_costiero_di_Ardea_le_terrecotte_del_tempio_arcaico_in_Tetti_di_Terracotta_La_decorazione_architettonica_fittile_tra_Etruria_e_Lazio_in_età_arcaica_Atti_delle_giornate_di_studio_Sapienza_Università_di_Roma_25_marzo_e_15_ottobre_2010_Officina_di_Etruscologia_5_Roma_2011_251_258`

You'll see a couple of à in there.

My Nokogiri knowledge is zero, so I can't fix it. :-(

**Comment by ryanfb** [comment]
Thanks! Should be fixed with the latest commit.
