### ISSUE TITLE
Feature request: add error messages

### ISSUE THREAD

**Issue by Jmuccigr** [ryanfb/academia-dl#2]
If the process that parses the URL could report an error (e.g., "not a URL" or "not an academia URL"), that would be great.

I put this in a MacOS service that I'll post and this would be helpful for when things go wrong.

**Comment by Jmuccigr** [comment]
Here's my shot at it:
```
ARGV.each do |academia_url|
  doc = nil
  tries = 0
    begin
    uri = Addressable::URI.parse(academia_url).normalize.to_s
    doc = Nokogiri::HTML(URI.open(uri))
  rescue OpenURI::HTTPError => e
    tries += 1
    if tries < 5
      sleep(5)
      retry
    else
      $stderr.puts 'URL problem:\n' + e.inspect
      exit
    end
  end
  begin
	download_url = doc.css('a.js-swp-download-button').first['href']
	download_id = download_url.split('/')[-2]
	filename = "#{URI(uri).path.split('/').last[0..250]}.pdf"
	url = "#{PREFIX}/#{download_id}/#{filename}"
  rescue
    $stderr.puts "Problem with the download. Here's what I was trying to get:\n<#{url}>"
  exit
  end
#   $stderr.puts "Resolved download URL: #{url}"
  if File.exist?("#{download_dir}/#{filename}")
    $stderr.puts "File already exists, skipping:\n#{filename}"
  else
    IO.copy_stream(open(url, OPEN_URI_OPTIONS), "#{download_dir}/#{filename}")
#     $stderr.puts "Downloaded #{filename}"
  end
end
```

(You'll notice that I've changed to download folder to be the standard MacOS one.)

I limited the number of retries on the URL and also tried to catch places where I had a problem. Admittedly I'm pushing things by trying it on text that obviously isn't correct. In the MacOS Service, I'm only using stderr where there are errors and a lack of feedback indicates success (and so the commented-out stderr puts). Conveniently the Automator filters the selected text for URLs, so I can catch irrelevant text before it hits your script.

**Comment by ryanfb** [comment]
Thanks, should handle most cases now.
